version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: Uro

  wordpress:
    image: wordpress:5.9.3-php7.4-apache
    depends_on:
      - mysql
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "80:80"

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    networks:
      - web_network
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "70:80"

networks:
  web_network:
